### PR TITLE
Fix GAP/SEC/SEM/BV-62-c to 67C

### PR DESCRIPTION
**Pull request by laxiLang**
These tests added a new MMI#108, requests
security enabled.

### CODE REVIEW

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/931#issuecomment-1568372264 after 14:48:54.

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/931#issuecomment-1568372264 after 15:01:13.

**Comment by laxiLang** [comment]
@mkasenberg : can you review this PR?

**Comment by mkasenberg** [comment]
@sjanc , is TSE18349 errata still in progress?

**Comment by laxiLang** [comment]
> @sjanc , is TSE18349 errata still in progress?

It has been released into TCRL-2022-2.

**Comment by laxiLang** [comment]
> @mkasenberg : can you review this PR?
We need this change for qualification. Can you review this change?

**Review by sjanc — CHANGES_REQUESTED** [review]
HI,

This is not a correct fix, we should fix GAP WID 108 handling instead to match what is expected by PTS 8.4.1

I fixed this (and couple other issues in https://github.com/auto-pts/auto-pts/pull/933)

**Pull request closed without merging**
