### PR TITLE
Revert "Zephyr: update workspace to PTS 8.1.0 (TCRL 2021-1)"

### PR DESCRIPTION
**Pull request by michal-narajowski**
Reverts intel/auto-pts#508

### CODE REVIEW

**Review by sjanc — APPROVED** [review]

**Comment by LingaoM** [comment]
why？

**Comment by sjanc** [comment]
this is temporary

PTS 8.1 included TCLR update, we want first to stabilize tests results within our test environment so that it is useful for regression tracking.   Once this is done and operational we will update to PTS 8.1.

**Comment by LingaoM** [comment]
Okay. So the current stable is 8.0.3?

**Comment by sjanc** [comment]
yeap

**Pull request merged**
