### PR TITLE
Common code

### PR DESCRIPTION
**Pull request by MariuszSkamra**
1. Fix for intel/auto-pts#342
2. Move l2cap/mesh wid handlers to common package

### CODE REVIEW

**Comment by MariuszSkamra** [comment]
@michal-narajowski FYI

**Comment by MariuszSkamra** [comment]
@tedd-an the long-term task is to get rid of the ptsprojects at all an have a common code for all implementations (zephyr/bluez/nimble etc.). The only thing that will be different will be overlay for doing reset, test case preconditions and PIXIT settings

**Comment by tedd-an** [comment]
Wait for zephyrproject-rtos/zephyr#19185 to be merged.

**Comment by MariuszSkamra** [comment]
@tedd-an the patch has been already merged

**Pull request merged**
