### PR TITLE
wid: Add support for L2CAP/LE/CFC/BV-25-C

### PR DESCRIPTION
**Pull request by ilhanates**
The PTS software (8.2.0) issues are fixed and expected to released
in next release.The new steps are added to the test to fullfil the
test specification properly.

Test steps:
1-IUT creates connection to PTS (PTS should be advertising)
2-PTS sends security request
3-IUT sends pairing request
4-Pairing complete (with bonding option, so LTK will be stored for coming
  connections)
- new step: Disconnect (WID=272)
- new step: Reconnect: IUT creates connection to PTS (same as step1)
- new WID=138 to make sure L2CAP channel encryption requrements before
the following request.

5-PTS sends L2CAP_LE_CREDIT_BASED_CONNECTION_REQ
6-IUT is expected to respond with result code as 0x08=Insufficient Encryption

See the PTS software case (CASE0072529) for more details. The fix patch
is shared as L2CAP.ets

### CODE REVIEW

**Comment by ilhanates** [comment]
This test was failing for the zephyr [issue ](https://github.com/zephyrproject-rtos/zephyr/issues/42862)

**Comment by ilhanates** [comment]
See the log
[L2CAP_LE_CFC_BV_25_C.zip](https://github.com/intel/auto-pts/files/8107457/L2CAP_LE_CFC_BV_25_C.zip)
s

**Comment by ilhanates** [comment]
@sjanc @AyturkDuzen  FYKI.

**Review by michal-narajowski — APPROVED** [review]

**Comment by ilhanates** [comment]
I will update the PR. Please wait to merge

**Comment by ilhanates** [comment]
> 
Do we put still even if the issue is resolved (i expect to be resolved today)?

**Comment by ilhanates** [comment]
Please merge.

**Review by michal-narajowski — APPROVED** [review]

**Comment by sjanc** [comment]
> Do we put still even if the issue is resolved (i expect to be resolved today)?
> btw, the test noted already one closed issue (CASE0072056: similar problem with current case) in errata.yml but has no fix.

yes, we want to track this until new PTS is released and fix is confirmed on released PTS

**Pull request merged**
