### PR TITLE
[Do not merge] Mynewt: add missing recovery arguments

### PR DESCRIPTION
**Pull request by KKopyscinski**
Without these tests won't run and client script will end up with error.

### CODE REVIEW

**Comment by KKopyscinski** [comment]
@michal-narajowski PTAL
@mkasenberg Is this all that's required for recovery support?

**Comment by KKopyscinski** [comment]
As discussed offline, this can exist here as workaround for now, but in near future `autoptsclient-{os}.py` files will be joined together into one client, which will solve the issue in proper way

**Comment by mringwal** [comment]
> As discussed offline, this can exist here as workaround for now, but in near future `autoptsclient-{os}.py` files will be joined together into one client, which will solve the issue in proper way

I've also run into this and added the new arguments to our fork. Unifying the autptsclient implementations would be great.

**Comment by michal-narajowski** [comment]
Resolved by https://github.com/intel/auto-pts/pull/474

**Pull request closed without merging**
