### PR TITLE
ptscontrol: Refactor server side to use PTS COM interface

### PR DESCRIPTION
**Pull request by MariuszSkamra**
This fixes issue we had using Interop.PTSControl.dll,
this dependency has been removed.
With this PTS COM is used directly via Dispatch based COM object.
The IronPython dependency has been removed so that run this
script with Python 3.

### CODE REVIEW

**Comment by MariuszSkamra** [comment]
@michal-narajowski FYI

**Comment by tedd-an** [comment]
Thanks. Let me run a test run tomorrow before merging it.

**Comment by MariuszSkamra** [comment]
@tedd-an updated

**Comment by tedd-an** [comment]
Test result with new change.
[report_pr315.txt](https://github.com/intel/auto-pts/files/3159632/report_pr315.txt)
[report_pr315.xlsx](https://github.com/intel/auto-pts/files/3159633/report_pr315.xlsx)

**Comment by MariuszSkamra** [comment]
@tedd-an Awesome!

**Pull request merged**
