### PR TITLE
Project structure

### PR DESCRIPTION
**Pull request by michal-narajowski**

### CODE REVIEW

**Comment by michal-narajowski** [comment]
#AutoPTS autotest run zephyr

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/intel/auto-pts/pull/711#issuecomment-1067847165 after 12:02:14.

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/intel/auto-pts/pull/711#issuecomment-1067847165 after 12:05:14.

**Comment by codecoup-tester** [comment]
Failed to merge the branch

**Comment by michal-narajowski** [comment]
#AutoPTS autotest run zephyr

**Comment by michal-narajowski** [comment]
#AutoPTS autotest run zephyr

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/intel/auto-pts/pull/711#issuecomment-1067922126 after 13:22:48.

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/intel/auto-pts/pull/711#issuecomment-1067975569 after 14:17:50.

**Comment by michal-narajowski** [comment]
#AutoPTS autotest run zephyr

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/intel/auto-pts/pull/711#issuecomment-1067992709 after 14:34:32.

**Pull request merged**
