### PR TITLE
zephyr: Update project to PTS 8.0.0

### PR DESCRIPTION
**Pull request by michal-narajowski**
- Add new testcases
- Update IXIT values
- Update test case names in SM after update to PTS 8.0.0
- Update zephyr-master workspace by opening it in PTS 8.0 in GUI mode and saving the changes

### CODE REVIEW

**Comment by michal-narajowski** [comment]
Depends on https://github.com/zephyrproject-rtos/zephyr/pull/31232

**Comment by michal-narajowski** [comment]
@trond-snekvik FYI

**Review by MariuszSkamra — APPROVED** [review]
LGTM

**Comment by michal-narajowski** [comment]
Depends on https://github.com/intel/auto-pts/pull/424

**Review by MariuszSkamra — APPROVED** [review]
LGTM. One minor comment to https://github.com/intel/auto-pts/pull/424

**Review by MariuszSkamra — APPROVED** [review]

**Pull request merged**
