### PR TITLE
common: Split pybtp/btp.py into multiple files

### PR DESCRIPTION
**Pull request by mkasenberg**
because it has already grown too much.

### CODE REVIEW

**Review by MariuszSkamra — APPROVED** [review]

**Review by michal-narajowski — APPROVED** [review]
LGTM

**Comment by mkasenberg** [comment]
I found a bug, when running with mynewt. Please wait a little more.

**Comment by mkasenberg** [comment]
Fixed, but I will run all test cases just in case I missed something else.

**Comment by mkasenberg** [comment]
It seems OK now.

**Comment by mkasenberg** [comment]
@michal-narajowski gave me great advice on how to split a module into multiple files without breaking backwards compatibility, so much less changes were needed.

**Review by michal-narajowski — APPROVED** [review]
LGTM

**Pull request merged**
