### PR TITLE
zephyr: Update workspace to PTS 8.2.3 and TCRL 2021-2

### PR DESCRIPTION
**Pull request by sjanc**

### CODE REVIEW

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/intel/auto-pts/pull/761#issuecomment-1161901784 after 03:18:34.

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/intel/auto-pts/pull/761#issuecomment-1161901784 after 09:06:01.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
Failed tests:
GAP     GAP/SEC/CSIGN/BI-03-C           INCONC
GAP     GAP/SEC/SEM/BV-62-C             INCONC - ERRATA TSE18349
GAP     GAP/SEC/SEM/BV-63-C             INCONC - ERRATA TSE18349
GAP     GAP/SEC/SEM/BV-64-C             INCONC - ERRATA TSE18349
GAP     GAP/SEC/SEM/BV-65-C             INCONC - ERRATA TSE18349
GAP     GAP/SEC/SEM/BV-66-C             FAIL - ERRATA TSE18349
GAP     GAP/SEC/SEM/BV-67-C             INCONC - ERRATA TSE18349
GATT    GATT/CL/GAR/BI-42-C             INCONC
GATT    GATT/CL/GAR/BV-10-C             FAIL
GATT    GATT/CL/GAR/BV-11-C             INCONC
GATT    GATT/CL/GPM/BV-11-C             FAIL
GATT    GATT/SR/GAN/BV-02-C             INCONC
GATT    GATT/SR/GAN/BV-02-C_LT2         FAIL
MESH    MESH/NODE/FRND/FN/BV-05-C       FAIL
MESH    MESH/NODE/FRND/FN/BV-06-C       INCONC
MESH    MESH/NODE/FRND/FN/BV-14-C       XML-RPC ERROR
MESH    MESH/NODE/IVU/BI-05-C           INCONC
MESH    MESH/NODE/IVU/BI-06-C           INCONC
MESH    MESH/NODE/IVU/BV-01-C           INCONC
MESH    MESH/NODE/IVU/BV-02-C           INCONC
MESH    MESH/NODE/IVU/BV-03-C           INCONC
MESH    MESH/NODE/IVU/BV-04-C           INCONC
MESH    MESH/NODE/IVU/BV-05-C           INCONC
MESH    MESH/NODE/KR/BI-05-C            INCONC
MESH    MESH/NODE/KR/BV-02-C            INCONC
MESH    MESH/NODE/KR/BV-03-C            INCONC
MESH    MESH/NODE/TNPT/BI-01-C          FAIL
MESH    MESH/NODE/TNPT/BV-04-C          FAIL
MESH    MESH/SR/PROX/BV-13-C            INCONC
MESH    MESH/SR/PROX/BV-14-C            FAIL
SM      SM/CEN/KDU/BI-02-C              INCONC - ERRATA SE17732 TSE17772
SM      SM/CEN/KDU/BI-03-C              INCONC - ERRATA SE17732 TSE17772
SM      SM/PER/KDU/BI-02-C              INCONC - ERRATA SE17732 TSE17772
SM      SM/PER/KDU/BI-03-C              BTP TIMEOUT - ERRATA SE17732 TSE17772

**Comment by hermabe** [comment]
- GATT GATT/CL/GAR/BI-42-C needs `BT_ATT_RETRY_ON_SEC_ERR=n` introduced in https://github.com/zephyrproject-rtos/zephyr/commit/c3c7b54ccf3cc9416ab712f0f89f83fc9e798426
-  GATT/CL/GAR/BV-(10, 11)-C Needs support in auto-pts for sending concurrent GATT requests
-  GATT/SR/GAN/BV-02-C(_LT2) We have seen issues with before related to two dongles being used. CASE0072153

**Pull request closed without merging**
