### PR TITLE
Some common updates, fixes and update of Mynewt project to PTS 7.5.1

### PR DESCRIPTION
**Pull request by michal-narajowski**

### CODE REVIEW

**Comment by michal-narajowski** [comment]
@MariuszSkamra Thanks, I added missing definitions to btp_spec.txt.

**Comment by MariuszSkamra** [comment]
@tedd-an Do you have a time to run the tests with this PR?

**Comment by michal-narajowski** [comment]
Most of these changes are Mynewt specific. There are only a few small changes that touch common code so the chance that they break something is small. Still it would be good if you could test it.

**Comment by MariuszSkamra** [comment]
@michal-narajowski I think there is no point to hold this PR from being merged. Even if @tedd-an reports it broke something, it can be fixed in following PR

**Pull request merged**
