### PR TITLE
wid: Fix GAP/BOND/BON/BV-04-C

### PR DESCRIPTION
**Pull request by sjanc**
This test was passing occasionally due to races in handling WID actions. Now explicitly wait for expected actions before returning from WID handler.

### CODE REVIEW

**Comment by sjanc** [comment]
#AutoPTS run zephyr GAP

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/intel/auto-pts/pull/856#issuecomment-1419277125 after 16:35:40.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
Failed tests:
GAP     GAP/SEC/SEM/BV-41-C             BTP ERROR
GAP     GAP/SEC/SEM/BV-42-C             BTP ERROR
GAP     GAP/SEC/SEM/BV-62-C             INCONC - ERRATA TSE18349
GAP     GAP/SEC/SEM/BV-63-C             INCONC - ERRATA TSE18349
GAP     GAP/SEC/SEM/BV-64-C             INCONC - ERRATA TSE18349
GAP     GAP/SEC/SEM/BV-65-C             FAIL - ERRATA TSE18349
GAP     GAP/SEC/SEM/BV-66-C             FAIL - ERRATA TSE18349
GAP     GAP/SEC/SEM/BV-67-C             FAIL - ERRATA TSE18349

**Comment by sjanc** [comment]
#AutoPTS run zephyr  GAP/SEC/SEM/BV-56-C GAP/SEC/SEM/BV-57-C GAP/SEC/SEM/BV-58-C GAP/SEC/SEM/BV-41-C GAP/SEC/SEM/BV-42-C GAP/BOND

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/intel/auto-pts/pull/856#issuecomment-1420474999 after 20:44:08.

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/intel/auto-pts/pull/856#issuecomment-1420474999 after 10:51:21.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.

**Comment by sjanc** [comment]
#AutoPTS run zephyr GAP

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/intel/auto-pts/pull/856#issuecomment-1420574506 after 11:54:24.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
Failed tests:
GAP     GAP/SEC/SEM/BV-62-C             INCONC - ERRATA TSE18349
GAP     GAP/SEC/SEM/BV-63-C             INCONC - ERRATA TSE18349
GAP     GAP/SEC/SEM/BV-64-C             INCONC - ERRATA TSE18349
GAP     GAP/SEC/SEM/BV-65-C             FAIL - ERRATA TSE18349
GAP     GAP/SEC/SEM/BV-66-C             INCONC - ERRATA TSE18349
GAP     GAP/SEC/SEM/BV-67-C             INCONC - ERRATA TSE18349

**Review by michal-narajowski — APPROVED** [review]

**Pull request merged**
