### PR TITLE
[ignore] Dummy commit. Do not merge

### PR DESCRIPTION
**Pull request by mkasenberg**
Cron testing

### CODE REVIEW

**Comment by mkasenberg** [comment]
#AutoPTS run mynewt L2CAP/COS/ECFC/BV-01-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/intel/auto-pts/pull/666#issuecomment-994670205 after 11:53:51.

**Comment by codecoup-tester** [comment]
Failed to merge the branch

**Comment by mkasenberg** [comment]
#AutoPTS run mynewt L2CAP/COS/ECFC/BV-01-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/intel/auto-pts/pull/666#issuecomment-994733226 after 13:15:38.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No regressions found.
Found progresses:
L2CAP   L2CAP/COS/ECFC/BV-01-C          PASS - PROGRESS

**Pull request closed without merging**
